apiVersion: v1
kind: Namespace
metadata:
  name: image-registry
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-registry-pvc
  namespace: image-registry
spec:
  storageClassName: "kubevirt-hostpath-provisioner"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-registry
  namespace: image-registry
  labels:
    app: image-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-registry
  template:
    metadata:
      labels:
        app: image-registry
    spec:
      volumes:
        - name: image-registry-storage
          persistentVolumeClaim:
            claimName: image-registry-pvc
      containers:
        - name: image-registry
          image: image-registry
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: image-registry-storage
              mountPath: /var/lib/registry
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: image-registry
  name: image-registry
  namespace: image-registry
spec:
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: image-registry
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: image-registry
  name: image-registry
  namespace: image-registry
spec:
  host: image-registry.global.ibm.tech.alliance
  port:
    targetPort: 5000
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: image-registry
    weight: 100
  wildcardPolicy: None