apiVersion: v1
kind: Namespace
metadata:
  name: image-registry
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-registry-pvc
  namespace: image-registry
spec:
  storageClassName: "kubevirt-hostpath-provisioner"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-registry
  namespace: image-registry
  labels:
    app: image-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-registry
  template:
    metadata:
      labels:
        app: image-registry
    spec:
      volumes:
        - name: image-registry-pvc-storage
          persistentVolumeClaim:
            claimName: image-registry-pvc
      containers:
        - name: image-registry
          image: registry
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: image-registry-pvc-storage
              mountPath: /var/lib/registry
---
apiVersion: v1
kind: Service
metadata:
  name: image-registry
  namespace: image-registry
spec:
  selector:
    app: image-registry
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5000